name:     gsu-physfac-timetable
version:  0.0.1
category: API
author:   Aliaksei Valatouski

library:
  source-dirs: src
  exposed-modules:
    - Gsu.Physfac.Common
    - Gsu.Physfac.Site.Pages.Download
    - Gsu.Physfac.Site.Pages.Home
    - Gsu.Physfac.Site.Pages.Repository
    - Gsu.Physfac.Site.Parser
    - Gsu.Physfac.Timetable.Document.ShrinkToFit
    - Gsu.Physfac.Timetable.Document.Xlsx
    - Gsu.Physfac.Timetable.Document.Xlsx.Parser
  dependencies:
    - aeson
    - base >= 4.10
    - bytestring
    - conduit
    - deepseq
    - exceptions
    - http-conduit
    - mtl
    - resourcet
    - text
    - vector
    - xml-conduit
    - xml-types
    - zip-archive
  default-extensions:
    - BlockArguments
    - DeriveAnyClass
    - DeriveGeneric
    - DerivingStrategies
    - GeneralizedNewtypeDeriving
    - LambdaCase
    - OverloadedStrings
    - RecordWildCards

executables:
  ptt:
    source-dirs: app
    main:        Main.hs
    ghc-options:
      - -O2
    other-modules:
      - Options
    dependencies:
      - aeson
      - aeson-pretty
      - base >= 4.10
      - bytestring
      - extra
      - gsu-physfac-timetable
      - http-conduit
      - optparse-applicative
      - text
    default-extensions:
      - BlockArguments
      - DerivingStrategies
      - RecordWildCards
      - TupleSections
